name: pothipatra
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+6

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^1.1.5
  google_fonts: 2.1.0
  flutter_share: ^2.0.0
  url_launcher: ^6.1.5
  modal_bottom_sheet: ^2.1.2
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^4.4.1+1
  http: ^0.13.5
  flutter_widget_from_html: ^0.8.5
  carousel_slider: ^4.1.1
  onesignal_flutter: ^3.5.0
  icons_launcher: ^2.0.6
  connectivity_plus: ^3.0.2
  pagination_view: ^2.0.0

icons_launcher:
  image_path: "assets/images/png/final_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/images/png/
    - assets/images/svg/
    - assets/images/gif/
    - assets/fonts/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins-black.ttf
        - asset: assets/fonts/poppins-blackItalic.ttf
        - asset: assets/fonts/poppins-bold.ttf
        - asset: assets/fonts/poppins-boldItalic.ttf
        - asset: assets/fonts/poppins-extraBold.ttf
        - asset: assets/fonts/poppins-light.ttf
        - asset: assets/fonts/poppins-medium.ttf
        - asset: assets/fonts/poppins-regular.ttf
        - asset: assets/fonts/poppins-semiBold.ttf
          weight: 700
